### ISSUE TITLE
Setup script has an issue if people have multiple Azure Pass accounts

### ISSUE THREAD

**Issue by sthoward0914** [ctesta-oneillmsft/xyz#31] opened 2021-07-08 13:48 UTC
# Module: 00
#### Step: 07

The script has the same issue with duplicate names that is called out in the issue raised at: https://github.com/ctesta-oneillmsft/xyz/issues/17 and the resolution is the same. Bringing the description here:

This script gives an error when a previous Azure Pass account exists under the email account used to log in to do the labs.
All Azure Pass Accounts have the same name by default. All of them are named "Azure Pass - Sponsorship." In my case, I had two old accounts, and the one used for this lab. In the script used in this step, it only lists the name of the subscriptions and asks the user to choose which one. We can't distinguish, and neither can the script. In this case, the script just gives a notice that more than one subscription by that name exists, and it tries to continue on with the first one in the list, and in my case, that was an old, disabled subscription, so the rest of the script is unsuccessful.
To work around this, I went to the script and modified the block of code to hard-code in my subscription-id. I think if the script referenced the subscription id instead of the subscription name, you could avoid this issue. The code as I modified it to work around (the subscription ID will not be valid when I'm through with this lab hack):
[snip beginning with line 52]
#Different approach to run automation in Cloud Shell
$subs = Get-AzSubscription | Select-Object -ExpandProperty Name
if($subs.GetType().IsArray -and $subs.length -gt 1){
$subOptions = [System.Collections.ArrayList]::new()
for($subIdx=0; $subIdx -lt $subs.length; $subIdx++){
$opt = New-Object System.Management.Automation.Host.ChoiceDescription "$($subs[$subIdx])", "Selects the $($subs[$subIdx]) subscription."
$subOptions.Add($opt)
}
$selectedSubIdx = $host.ui.PromptForChoice('Enter the desired Azure Subscription for this lab','Copy and paste the name of the subscription to make your choice.', $subOptions.ToArray(),0)
$selectedSubName = $subs[$selectedSubIdx]
Write-Information "Selecting the $selectedSubName subscription"
#Select-AzSubscription -SubscriptionName $selectedSubName
            Select-AzSubscription -SubscriptionId '257b6951-3d5e-49ec-96bc-406f08a272aa'

            #az account set --subscription $selectedSubName
            az account set --subscription '257b6951-3d5e-49ec-96bc-406f08a272aa'
    } 
[/snip beginning with line 52]
Repro steps:
1.	Have more than one Azure Pass Subscription on your email address
2.	Work through to the indicated step
3.	See the errors
As an alternative, you might be able to add a step to have the students change the name of their subscription.

**Comment by ctesta-oneillmsft** [comment] 2021-07-09 14:34
After a discussion with the team we have decided not to implement this. Concerns have been expressed with people running powershell scripts as it is. To get them modify the script itself with a hard coded subscription id risks the students causing more issues with the setup. Therefore closing as by design

**Closed by ctesta-oneillmsft** 2021-07-09 14:34 UTC

**Comment by sthoward0914** [comment] 2021-07-15 12:47
I think that missed the point. I was not asking to have it changed to hard code the subscription ID. Quite the contrary. As it is, we WILL BE fighting this battle in EVERY class with MULTIPLE students, and the only way we have to work around it is to have them change the script IN CLASS to hard code their subscription ID in it.

What I am suggesting is that the script be changed so that the students have a way to choose one particular subscription ID from a list of subscriptions that all have the same name. As it currently is, all of these subscriptions have the same name, and since the script uses name instead of subscription ID, it will error out at that point giving an error that tells them there are multiple subscriptions by that name.

Chris, this is going to be a disaster at the beginning of every class if it is not changed. If you need clarification, please reach out to me, or bring me into the discussion, but this cannot be left as it is.

**Comment by GraemeMalcolm** [comment] 2021-07-15 14:25
I'll be updating the setup script today, and will address this as I do so.

**Comment by sthoward0914** [comment] 2021-07-15 19:58
Thank you, Graeme.
