### ISSUE TITLE
Module 0: Task 2: Step 7: Select the default values for the cluster configuration.

### ISSUE THREAD

**Issue by chris-utter** [ctesta-oneillmsft/xyz#20] opened 2021-07-07 16:55 UTC
Azure Pass Subscriptions have a Total Regional vCPU quota of 10 (or 12). 
Depending on the total number of vcores available, even a 1-2 worker cluster using the smallest available cluster vm (4 cores) would be too big (12 cores).

1. Using the attached Databricks cluster screenshot will fail due to lack of available vCPUs. Recommend A) disabling autoscale and setting workers to 1, or B) using a Single Node cluster.

2. Using Spot instances NOT recommended with small clusters (see above). Spot instances can terminate at any time.

**Comment by joelhulen** [comment] 2021-07-07 16:58
I agree that we want to go down to a single node cluster and NOT use spot instances.

**Comment by ctesta-oneillmsft** [comment] 2021-07-08 08:49
I tested the course using an Azure Pass with no errors. There are also instructions to start and terminate clusters when no in use. SO closing this as by design

**Closed by ctesta-oneillmsft** 2021-07-08 08:49 UTC
