### ISSUE TITLE
Multiple Azure Pass subscriptions in the personal email address causes an error running the setup script

### ISSUE THREAD

**Issue by sthoward0914** [ctesta-oneillmsft/xyz#17] opened 2021-07-07 13:41 UTC
# Module: 00
#### Step: 09

This script gives an error when a previous Azure Pass account exists under the email account used to log in to do the labs.

All Azure Pass Accounts have the same name by default. All of them are named "Azure Pass - Sponsorship." In my case, I had two old accounts, and the one used for this lab. In the script used in this step, it only lists the name of the subscriptions and asks the user to choose which one. We can't distinguish, and neither can the script. In this case, the script just gives a notice that more than one subscription by that name exists, and it tries to continue on with the first one in the list, and in my case, that was an old, disabled subscription, so the rest of the script is unsuccessful.

To work around this, I went to the script and modified the block of code to hard-code in my subscription-id. I think if the script referenced the subscription id instead of the subscription name, you could avoid this issue. The code as I modified it to work around (the subscription ID will not be valid when I'm through with this lab hack):

[snip beginning with line 52]
        #Different approach to run automation in Cloud Shell
        $subs = Get-AzSubscription | Select-Object -ExpandProperty Name
        if($subs.GetType().IsArray -and $subs.length -gt 1){
                $subOptions = [System.Collections.ArrayList]::new()
                for($subIdx=0; $subIdx -lt $subs.length; $subIdx++){
                        $opt = New-Object System.Management.Automation.Host.ChoiceDescription "$($subs[$subIdx])", "Selects the $($subs[$subIdx]) subscription."
                        $subOptions.Add($opt)
                }
                $selectedSubIdx = $host.ui.PromptForChoice('Enter the desired Azure Subscription for this lab','Copy and paste the name of the subscription to make your choice.', $subOptions.ToArray(),0)
                $selectedSubName = $subs[$selectedSubIdx]
                Write-Information "Selecting the $selectedSubName subscription"
                #Select-AzSubscription -SubscriptionName $selectedSubName

                Select-AzSubscription -SubscriptionId '257b6951-3d5e-49ec-96bc-406f08a272aa'

                #az account set --subscription $selectedSubName
                az account set --subscription '257b6951-3d5e-49ec-96bc-406f08a272aa'
        } 
[/snip beginning with line 52]

Repro steps:

1. Have more than one Azure Pass Subscription on your email address
2. Work through to the indicated step
3. See the errors

As an alternative, you might be able to add a step to have the students change the name of their subscription.

**Comment by vasuja515** [comment] 2021-07-07 17:49
When it comes to selecting the subscription, some customers will come in with multiple "Azure Pass" subscriptions from other classes. We may need to add a powershell script to specify the sub ID vs the name, or add a note for a customer to create a new email which does not have an Azure Pass associated with it for an easier deployment.

**Comment by ctesta-oneillmsft** [comment] 2021-07-08 21:51
closing as a duplicate of #31

**Closed by ctesta-oneillmsft** 2021-07-08 21:51 UTC
