### ISSUE TITLE
Module 10 - Real-time stream processing with Stream Analytics - Exercise 1 - Task 3 - Step 13 - asa.sql.admin user password has not been set by the students

### ISSUE THREAD

**Issue by annav88** [ctesta-oneillmsft/xyz#29] opened 2021-07-08 12:35 UTC
# Module: 10
#### Step: 13

Description of issue

In the instructions we say that we need to use the password that we set up during Lab 0 setup phase for the SQL user **asa.sql.admin** for the when configuring an output for the Stream Analytics job. However when running the script I did not set up any password, so the students will have to reset the SQL admin user password before setting up the Stream Analytics job output in this step.

Please see the screenshot showing it.

![lab10_ex1_task3_point13](https://user-images.githubusercontent.com/83666021/124922439-ca5ee700-dff9-11eb-8010-51e4e46888e6.png)

Thank you,
Anna

**Comment by ctesta-oneillmsft** [comment] 2021-07-08 12:47
This is set by the student during the setup, and we ask in the instruction during the setup to keep a note of the password for future use

![image1](https://user-images.githubusercontent.com/33545180/124924115-02166080-dff3-11eb-840c-a2836d7b868c.png)

and then we remind them to use that password in the lab.

![image2](https://user-images.githubusercontent.com/33545180/124924167-0e9ab900-dff3-11eb-9811-a1f23700751d.png)

so closing as by design

**Closed by ctesta-oneillmsft** 2021-07-08 12:47 UTC
